# Generated by Django 5.0.4 on 2024-04-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('count', models.PositiveIntegerField()),
                ('buy_price', models.PositiveIntegerField()),
                ('sell_price', models.PositiveIntegerField()),
            ],
        ),
    ]
